# Generated by Django 4.2 on 2024-12-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytrans',
            options={'managed': True},
        ),
    ]
