# Generated by Django 4.2 on 2024-12-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_dailytrans_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytrans',
            name='date_time',
            field=models.DateField(),
        ),
    ]
