# Generated by Django 4.2 on 2024-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_dailytrans_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrans',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
