# Generated by Django 4.2 on 2024-12-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_dailytrans_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytrans',
            name='months',
        ),
        migrations.RemoveField(
            model_name='dailytrans',
            name='years',
        ),
    ]
