# Generated by Django 4.2 on 2024-12-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_dailytrans_months_remove_dailytrans_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytrans',
            name='slug',
        ),
    ]
