# Generated by Django 4.2 on 2024-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_dailytrans_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytrans',
            name='subcategories',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
